[package]
name = "slog-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog-json = "2.6.1"
slog = "2.7.0"
slog-async = "2.7"
